const { chromium } = require('playwright');
const path = require('node:path');
const fs = require('node:fs');
const output = process.env.PREVIEW_DIR || path.resolve(__dirname, '../test-results');
fs.mkdirSync(output, {recursive:true});
(async () => {
 const browser = await chromium.launch({headless:true});
 const page = await browser.newPage({viewport:{width:1280,height:900}});
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 await page.goto('file://'+path.resolve(__dirname,'../index.html'));
 await page.evaluate(()=>{window.requestAnimationFrame=()=>{};});
 await page.waitForTimeout(100);
 const result=await page.evaluate(()=>{
  const passed=[]; const check=(v,n)=>{if(!v)throw Error(n);passed.push(n);};
  eventSettings={start:12,interval:4,duration:1};
  check(scheduledEvent(new Date(2026,8,30,12))==='normal','noon normal');
  check(scheduledEvent(new Date(2026,8,30,15,59))==='normal','warmup normal');
  check(scheduledEvent(new Date(2026,8,30,16))!=='normal','16:00 event starts');
  check(scheduledEvent(new Date(2026,8,30,17))==='normal','17:00 event ends');
  check(scheduledEvent(new Date(2026,8,30,20))!=='normal','20:00 next event');
  check(scheduledEvent(new Date(2026,9,1,0))!=='normal','midnight event');
  currentLevel=0;playerCount=1;difficultyIdx=0;startGame();
  runFrames=1799;player.coinScore=20;distanceScore=100;updateRunExtras();
  check(reviveHearts===3,'three challenges award three hearts');updateRunExtras();
  check(reviveHearts===3,'rewards cannot repeat');
  testingMode=false;player.lives=1;killPlayerObj(player);
  check(gameState===STATE.DEAD,'last life ends run');
  const bank=saveData.bank;reviveRunPlayer();
  check(player.alive&&player.lives===1&&reviveHearts===2,'heart revives player');
  bankCoins();check(saveData.bank===bank,'revive does not double bank');
  player.coinScore+=7;bankCoins();check(saveData.bank===bank+7,'only new coins banked');
  startGame();check(reviveHearts===0,'new run resets hearts');
  currentLevel=10;levelDuration=18000;levelTimeLeft=301;spawnBoss();
  const key=code=>({code,repeat:false,preventDefault(){}});
  handleExpansionKey(key('KeyK'));handleExpansionKey(key('KeyF'));
  check(!secretActive,'secret rejected before final five seconds');secretKeys.clear();
  levelTimeLeft=300;handleExpansionKey(key('KeyF'));handleExpansionKey(key('KeyK'));
  check(secretActive&&secretFrames===3600,'either key order unlocks 60 second vault');
  for(let i=0;i<110;i++)collectRunCoin(player);
  check(secretEarned===10000&&player.coinScore===10000,'vault capped at 10000');
  difficultyIdx=2;const before=saveData.bank;bankCoins();check(saveData.bank===before+10000,'difficulty cannot multiply vault reward');
  secretFrames=1;updateLevelProgress();check(gameState===STATE.VICTORY_WAIT&&!secretActive,'vault returns to campaign victory');
  playerCount=2;startGame();reviveHearts=1;player2.lives=1;killPlayerObj(player2);reviveRunPlayer();
  check(player2.alive&&!player2.permanentlyDead&&reviveHearts===0,'co-op revive');
  eventOverride='coins';obstacles.push({});updateRunExtras();check(obstacles.length===0,'coin shower clears hazards');
  eventOverride='double';updateRunExtras();player.coinScore=0;collectRunCoin(player);check(player.coinScore===2,'double coin award');
  eventOverride='spice';player.spice=1;updateRunExtras();check(player.spice===100,'spice event refuels');
  paused=true;const ticks=runFrames;update();check(runFrames===ticks,'pause freezes challenge timer');paused=false;
  openEventDirector();check(paused&&eventDialog.open,'director pauses play');closeEventDirector();check(!paused,'director resumes play');
  render();return passed;
 });
 console.log(result.map(x=>'PASS '+x).join('\n'));
 await page.keyboard.press('g');
 await page.screenshot({path:path.join(output,'preview-events.png')});
 await page.keyboard.press('g');
 await page.evaluate(()=>{playerCount=1;currentLevel=0;startGame();runFrames=900;player.coinScore=12;distanceScore=45;render();});
 await page.screenshot({path:path.join(output,'preview-game.png')});
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>render());
 await page.screenshot({path:path.join(output,'preview-mobile.png')});
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS no browser runtime errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
